### ISSUE TITLE
Can't find `.modelstar/session.registry.yaml` 

### ISSUE THREAD

**Issue by helincao** [modelstar-labs/modelstar#2]
#### Environment:
Python version: 3.0

#### How to reproduce:
Cloned the master branch;
Installed the new version;
Run `> modelstar init my_project`;
See the following errors.

#### Error message:
Traceback (most recent call last):
  File "/Users/helix/Library/Caches/pypoetry/virtualenvs/modelstar-DLhzjXZT-py3.9/bin/modelstar", line 3, in <module>
    from modelstar.cli import main
  File "/Users/helix/Documents/modelstar/modelstar/src/modelstar/__init__.py", line 6, in <module>
    session_registry = SessionRegistry()
  File "/Users/helix/Documents/modelstar/modelstar/src/modelstar/utils/logging.py", line 56, in __init__
    self.load_registry()
  File "/Users/helix/Documents/modelstar/modelstar/src/modelstar/utils/logging.py", line 63, in load_registry
    with open(self.file_path, 'w') as doc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/helix/Documents/modelstar/.modelstar/session.registry.yaml'

**Comment by helincao** [comment]
Updated Modelstar to v0.3.0, run `> modelstar init sales_forecast`, saw this error:



  Project not initialized.

  There are files in the current folder that conflict with the project initialization.
Traceback (most recent call last):
  File "/Users/helix/Library/Caches/pypoetry/virtualenvs/modelstar-DLhzjXZT-py3.9/lib/python3.9/site-packages/modelstar/commands/project.py", line 17, in initialize_project
    os.mkdir(os.path.join(project_folder_path, '.modelstar'))
FileExistsError: [Errno 17] File exists: '/Users/helix/Documents/modelstar/sales_forecast/.modelstar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/helix/Library/Caches/pypoetry/virtualenvs/modelstar-DLhzjXZT-py3.9/bin/modelstar", line 8, in <module>
    sys.exit(main())
  File "/Users/helix/Library/Caches/pypoetry/virtualenvs/modelstar-DLhzjXZT-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/helix/Library/Caches/pypoetry/virtualenvs/modelstar-DLhzjXZT-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/helix/Library/Caches/pypoetry/virtualenvs/modelstar-DLhzjXZT-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/helix/Library/Caches/pypoetry/virtualenvs/modelstar-DLhzjXZT-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/helix/Library/Caches/pypoetry/virtualenvs/modelstar-DLhzjXZT-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/helix/Library/Caches/pypoetry/virtualenvs/modelstar-DLhzjXZT-py3.9/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/helix/Library/Caches/pypoetry/virtualenvs/modelstar-DLhzjXZT-py3.9/lib/python3.9/site-packages/modelstar/cli.py", line 42, in init
    project_path = initialize_project(project_name=project_name)
  File "/Users/helix/Library/Caches/pypoetry/virtualenvs/modelstar-DLhzjXZT-py3.9/lib/python3.9/site-packages/modelstar/commands/project.py", line 23, in initialize_project
    raise FileExistsError(e)
FileExistsError: [Errno 17] File exists: '/Users/helix/Documents/modelstar/sales_forecast/.modelstar'

**Comment by helincao** [comment]
Just to mention that the project seems to be created properly. I can run other command. Just this error message seems odd.

**Comment by krish-adi** [comment]
Did the folder already exist before you created the project?

**Comment by helincao** [comment]
No

**Comment by krish-adi** [comment]
This should be resolved in V 0.3.1. But I couldn't replicate the exact error.
